server:
  port: 9090
spring:
  aop:
    auto: true
    proxy-target-class: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5
    encoding: UTF-8
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    ##时间戳统一转换
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: footman-app

es:
  host: 10.110.4.12
  port: 9200
  scheme: http
page:
  pageNum: 0
  pageSize: 20